language: python
python:
 - "3.5"

branches:
  only:
    - master

install:
 - pip install -r requeriments.txt

script: mkdocs build web/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: web/
  on:
    branch: master
