site_name: El rincón vacío

site_url: https://jpcarmona.github.io/web/

repo_url: https://github.com/jpcarmona/

edit_uri: '?query=root/path/docs/'

copyright: '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
            <img alt="Licencia Creative Commons" style="border-width:0" 
            src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>
            <br />Esta obra está bajo una 
            <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
            Licencia Creative Commons Atribución 4.0 Internacional</a>'

google_analytics: ['UA-36723568-3', 'mkdocs.org']

nav:
    - Home: index.md
    - MkDocs: mkdocs.md
    - About: about.md

theme: flatly

