# Información del proyecto
site_name: 'El Rincón Vacío'
site_description: 'El sitio de la informática'
site_author: 'Juan Pedro Carmona Romero'
site_url: 'https://jpcarmona.github.io/web/'

# Repositorio
repo_name: 'jpcarmona/generadormkdocs'
repo_url: 'https://github.com/jpcarmona/generadormkdocs'

#edit_uri: '?query=root/path/docs/blog/'

# ver urls
#use_directory_urls: false

# Copyright
copyright: '<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
            <img alt="Licencia Creative Commons" style="border-width:0" 
            src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a>
            <br />Esta obra está bajo una 
            <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
            Licencia Creative Commons Atribución 4.0 Internacional</a>'

google_analytics: ['UA-36723568-3', 'mkdocs.org']

# Configuración
theme: 
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/favicon.ico'
  favicon: 'img/favicon.ico'
  language: 'es'
  feature:
    tabs: true

# Configuración
extra:
  search:
    language: 'en, es'
  social:
    - type: 'github'
      link: 'https://github.com/jpcarmona/'
    - type: 'twitter'
      link: 'https://twitter.com/JPCR92'
    - type: 'linkedin'
      link: 'https://linkedin.com'
#  disqus: 'your-shortname' ## para comentarios

# Extensiones
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true

# CSS Extra
extra_css:
    - css/extra.css

#Navegación
nav:
- Inicio: 'index.md'
- Blog:
    - 'MkDocs': 'blog/mkdocs.md'
    - 'Kernel Linux': 'blog/kernel.md'
    - 'PL/SQL vs PL/PGSQL': 'blog/plpgsql.md'
    - 'Install Oracle 12': 'blog/oracleinstall.md'
    - 'Fail2Ban': 'blog/fail2ban.md'
    - 'Acceso remoto Postgresql': 'blog/postgresclient.md'
    - 'Cifrado y firmas con GPG': 'blog/gpg.md'
    - 'Interconexión de BBDD': 'blog/BBDD_1.md'
- Sobre mí: 'about.md'
